-- IoT Database Schema converted from Oracle CIMS
-- Clean SQLite version of key IoT tables

-- Signal Item - Core signal/sensor definitions
CREATE TABLE IF NOT EXISTS SIGNALITEM (
    SIGID INTEGER PRIMARY KEY,
    SIGNAME TEXT NOT NULL,
    ALIASNAME TEXT,
    CHANNR INTEGER,
    IOGROUP INTEGER DEFAULT 1,
    SIGTYPE INTEGER,
    DATATYPE INTEGER,
    OBJDESCR TEXT,
    OBJUNIT TEXT,
    OBJSCALE REAL,
    CTROVERFLOW INTEGER,
    DEFDATE DATETIME,
    ATMODIFIER TEXT,
    ATCREDATE DATETIME,
    ATCREATOR TEXT,
    MINVALUE REAL,
    MAXVALUE REAL
);

-- Signal Channel - Communication channels for signals
CREATE TABLE IF NOT EXISTS SIGNALCHANNEL (
    CHANNR INTEGER PRIMARY KEY,
    CHANNAME TEXT NOT NULL,
    ALIASNAME TEXT,
    SIGPROTID INTEGER,
    SLAVE INTEGER DEFAULT 0,
    DEFLOGCLASS TEXT,
    CHANDESCR TEXT,
    GROUPNR INTEGER DEFAULT 0,
    HOSTNAME TEXT,
    PROGID TEXT,
    HDAPROGID TEXT,
    EXTSYNCHRO INTEGER DEFAULT 1,
    WDOGSIGID INTEGER,
    WDOGLIMIT INTEGER,
    WDOGINSIGID INTEGER,
    WDOGINLIMIT INTEGER,
    WDOGLINKED INTEGER DEFAULT 0,
    STATUSSIGID INTEGER,
    DEFDATE DATETIME,
    ATMODIFIER TEXT,
    ATCREDATE DATETIME,
    ATCREATOR TEXT,
    USERNAME TEXT,
    PASSWORD TEXT,
    EXTERNALREPO INTEGER,
    EXTREPOTIMEOUT INTEGER
);

-- Signal Values - Current/latest signal values
CREATE TABLE IF NOT EXISTS SIGNALVALUE (
    SIGID INTEGER,
    UPDATETIME DATETIME,
    SIGNUMVALUE REAL,
    SIGTEXTVALUE TEXT,
    SIGSTATUS INTEGER DEFAULT 0,
    PRIMARY KEY (SIGID, UPDATETIME)
);

-- Report Data - Historical signal data storage
CREATE TABLE IF NOT EXISTS REPDATA (
    PINSTID INTEGER,
    RICODE INTEGER,
    NUMVALUE REAL,
    TEXTVALUE TEXT,
    PCTQUAL REAL,
    AUXVAL1 REAL,
    AUXVAL2 REAL,
    AUXVAL3 REAL,
    SORTNAME TEXT,
    SAMPLELOC TEXT,
    PLCFACTOR REAL,
    ORDERID TEXT,
    TASKID TEXT,
    DUMMY TEXT,
    PRIMARY KEY (PINSTID, RICODE)
);

-- Report Item - Report/calculation definitions 
CREATE TABLE IF NOT EXISTS REPITEM (
    RICODE INTEGER PRIMARY KEY,
    RICLASS TEXT,
    LOGCLASS TEXT,
    RITEXT TEXT,
    ALIASNAME TEXT,
    RIUNIT TEXT,
    RIDECIMALS INTEGER,
    RISCALE REAL,
    PLCRICODE TEXT,
    PLCRICODE2 TEXT,
    PLCRICODE3 TEXT,
    PLCRICODE4 TEXT,
    PLCRICODE5 TEXT,
    VSIGID1 INTEGER,
    VSIGID2 INTEGER,
    VSIGID3 INTEGER,
    VSIGID4 INTEGER,
    VSIGID5 INTEGER,
    VSIGID6 INTEGER,
    VSIGID7 INTEGER,
    VSIGID8 INTEGER,
    VSIGID9 INTEGER,
    VSIGID10 INTEGER,
    CSIGID1 INTEGER,
    CSIGID2 INTEGER,
    CSIGID3 INTEGER,
    SORTRICODE TEXT,
    AUXNUMVAL1 REAL,
    AUXNUMVAL2 REAL,
    AUXNUMVAL3 REAL,
    AUXNUMVAL4 REAL,
    AUXNUMVAL5 REAL,
    AUXNUMVAL6 REAL,
    AUXNUMVAL7 REAL,
    AUXDATEVAL1 DATETIME,
    AUXDATEVAL2 DATETIME,
    CUMPTYPE TEXT,
    CUMRICODE INTEGER,
    OSIGID1 INTEGER,
    LIMITID INTEGER,
    LOCID INTEGER,
    MSIGID INTEGER,
    DEADBAND REAL,
    STOPLOG INTEGER,
    DESCRIPTION TEXT,
    EXTGUID TEXT,
    DEFDATE DATETIME,
    ATMODIFIER TEXT,
    ATCREDATE DATETIME,
    ATCREATOR TEXT,
    LIMITLOG INTEGER,
    LIMITPTYPE TEXT,
    LIMITLEVEL INTEGER
);

-- Address - External system addresses
CREATE TABLE IF NOT EXISTS ADDRESS (
    ADDRID INTEGER PRIMARY KEY,
    ADDRNAME TEXT NOT NULL,
    ALIASNAME TEXT,
    ADDR TEXT,
    REMOTEURL TEXT,
    NODENR INTEGER,
    DESCRIPTION TEXT,
    DEFDATE DATETIME,
    ATMODIFIER TEXT,
    ATCREDATE DATETIME,
    ATCREATOR TEXT
);

-- Channel Groups - Logical grouping of channels
CREATE TABLE IF NOT EXISTS CHANNELGROUP (
    GROUPNR INTEGER PRIMARY KEY,
    GROUPNAME TEXT NOT NULL,
    ALIASNAME TEXT,
    NODENR INTEGER,
    DESCRIPTION TEXT,
    BUFFERED INTEGER DEFAULT 0,
    FASTDATAAC INTEGER DEFAULT 0,
    FDATIMESLOT INTEGER DEFAULT 1000,
    DEFDATE DATETIME,
    ATMODIFIER TEXT,
    ATCREDATE DATETIME,
    ATCREATOR TEXT
);

-- Process Instance - Time periods for data collection
CREATE TABLE IF NOT EXISTS PROCINSTANCE (
    PINSTID INTEGER PRIMARY KEY,
    PINSTSTART DATETIME,
    PINSTEND DATETIME,
    PTYPE TEXT,
    CLOSED INTEGER DEFAULT 0,
    VALID INTEGER DEFAULT 1,
    PINSTNAME TEXT,
    DESCRIPTION TEXT,
    CREDATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_signalvalue_sigid ON SIGNALVALUE(SIGID);
CREATE INDEX IF NOT EXISTS idx_signalvalue_time ON SIGNALVALUE(UPDATETIME);
CREATE INDEX IF NOT EXISTS idx_repdata_pinstid ON REPDATA(PINSTID);
CREATE INDEX IF NOT EXISTS idx_repdata_ricode ON REPDATA(RICODE);
CREATE INDEX IF NOT EXISTS idx_signalitem_name ON SIGNALITEM(SIGNAME);
CREATE INDEX IF NOT EXISTS idx_signalchannel_name ON SIGNALCHANNEL(CHANNAME);